REPUBLIC_MATRIX = {
    0: "stranac",
    1: "Bosna i Hercegovina",
    2: "Crna Gora",
    3: "Hrvatska",
    4: "Severna Makedonija",
    5: "Slovenija",
    6: "privremeni boravak",
    7: "uža Srbija",
    8: "Vojvodina",
    9: "Kosovo i Metohija",
}

REGION_MATRIX = {
    "00": "mešana upotreba",
    "01": "stranci u Bosni i Hercegovini",
    "02": "stranci u Crnoj Gori",
    "03": "stranci u Hrvatskoj",
    "04": "stranci u Severnoj Makedoniji",
    "05": "stranci u Sloveniji",
    "07": "stranci u užoj Srbiji",
    "08": "stranci u Vojvodini",
    "09": "stranci na Kosovu i Metohiji",
    "10": f"{REPUBLIC_MATRIX.get(1)}, Banja Luka",
    "11": f"{REPUBLIC_MATRIX.get(1)}, Bihać",
    "12": f"{REPUBLIC_MATRIX.get(1)}, Doboj",
    "13": f"{REPUBLIC_MATRIX.get(1)}, Goražde",
    "14": f"{REPUBLIC_MATRIX.get(1)}, Livno",
    "15": f"{REPUBLIC_MATRIX.get(1)}, Mostar",
    "16": f"{REPUBLIC_MATRIX.get(1)}, Prijedor",
    "17": f"{REPUBLIC_MATRIX.get(1)}, Sarajevo",
    "18": f"{REPUBLIC_MATRIX.get(1)}, Tuzla",
    "19": f"{REPUBLIC_MATRIX.get(1)}, Zenica",
    "21": f"{REPUBLIC_MATRIX.get(2)}, Podgorica",
    "22": f"{REPUBLIC_MATRIX.get(2)}, Bar, Ulcinj",
    "23": f"{REPUBLIC_MATRIX.get(2)}, Budva, Kotor, Tivat",
    "24": f"{REPUBLIC_MATRIX.get(2)}, Herceg Novi",
    "25": f"{REPUBLIC_MATRIX.get(2)}, Cetinje",
    "26": f"{REPUBLIC_MATRIX.get(2)}, Nikšić",
    "27": f"{REPUBLIC_MATRIX.get(2)}, Berane, Rožaje, Plav, Andrijevica",
    "28": f"{REPUBLIC_MATRIX.get(2)}, Bijelo Polje, Mojkovac",
    "29": f"{REPUBLIC_MATRIX.get(2)}, Pljevlja, Žabalj",
    "30": f"{REPUBLIC_MATRIX.get(3)}, Osijek",
    "31": f"{REPUBLIC_MATRIX.get(3)}, Bjelovar, Virovitica, Koprivnica, Pakrac",
    "32": f"{REPUBLIC_MATRIX.get(3)}, Varaždin, Međimurje",
    "33": f"{REPUBLIC_MATRIX.get(3)}, Zagreb",
    "34": f"{REPUBLIC_MATRIX.get(3)}, Karlovac",
    "35": f"{REPUBLIC_MATRIX.get(3)}, Lika",
    "36": f"{REPUBLIC_MATRIX.get(3)}, Istra, Primorje",
    "37": f"{REPUBLIC_MATRIX.get(3)}, Sisak, Banija",
    "38": f"{REPUBLIC_MATRIX.get(3)}, Dalmacija",
    "39": f"{REPUBLIC_MATRIX.get(3)}, mešana upotreba",
    "41": f"{REPUBLIC_MATRIX.get(4)}, Bitolj",
    "42": f"{REPUBLIC_MATRIX.get(4)}, Kumanovo",
    "43": f"{REPUBLIC_MATRIX.get(4)}, Ohrid",
    "44": f"{REPUBLIC_MATRIX.get(4)}, Prilep",
    "45": f"{REPUBLIC_MATRIX.get(4)}, Skoplje",
    "46": f"{REPUBLIC_MATRIX.get(4)}, Strumica",
    "47": f"{REPUBLIC_MATRIX.get(4)}, Tetovo",
    "48": f"{REPUBLIC_MATRIX.get(4)}, Veles",
    "49": f"{REPUBLIC_MATRIX.get(4)}, Štip",
    "50": f"{REPUBLIC_MATRIX.get(5)}",
    "60": f"{REPUBLIC_MATRIX.get(6)}",
    "70": f"{REPUBLIC_MATRIX.get(7)}, Građani upisani u Matičnu knjigu rođenih Diplomatsko Konzularnog Predstavništva Republike Srbije",
    "71": f"{REPUBLIC_MATRIX.get(7)}, Beograd",
    "72": f"{REPUBLIC_MATRIX.get(7)}, Kragujevac, Jagodina",
    "73": f"{REPUBLIC_MATRIX.get(7)}, Niš, Pirot, Toplica",
    "74": f"{REPUBLIC_MATRIX.get(7)}, Leskovac, Vranje",
    "75": f"{REPUBLIC_MATRIX.get(7)}, Zaječar, Bor",
    "76": f"{REPUBLIC_MATRIX.get(7)}, Smederevo, Požarevac",
    "77": f"{REPUBLIC_MATRIX.get(7)}, Mačva, Kolubara",
    "78": f"{REPUBLIC_MATRIX.get(7)}, Čačak, Kraljevo, Kruševac",
    "79": f"{REPUBLIC_MATRIX.get(7)}, Užice",
    "80": f"{REPUBLIC_MATRIX.get(8)}, Novi Sad",
    "81": f"{REPUBLIC_MATRIX.get(8)}, Sombor",
    "82": f"{REPUBLIC_MATRIX.get(8)}, Subotica",
    "83": f"{REPUBLIC_MATRIX.get(8)}, Vrbas",
    "84": f"{REPUBLIC_MATRIX.get(8)}, Kikinda",
    "85": f"{REPUBLIC_MATRIX.get(8)}, Zrenjanin",
    "86": f"{REPUBLIC_MATRIX.get(8)}, Pančevo",
    "87": f"{REPUBLIC_MATRIX.get(8)}, Vršac",
    "88": f"{REPUBLIC_MATRIX.get(8)}, Ruma",
    "89": f"{REPUBLIC_MATRIX.get(8)}, Sremska Mitrovica",
    "91": f"{REPUBLIC_MATRIX.get(9)}, Priština",
    "92": f"{REPUBLIC_MATRIX.get(9)}, Kosovska Mitrovica",
    "93": f"{REPUBLIC_MATRIX.get(9)}, Peć",
    "94": f"{REPUBLIC_MATRIX.get(9)}, Đakovica",
    "95": f"{REPUBLIC_MATRIX.get(9)}, Prizren",
    "96": f"{REPUBLIC_MATRIX.get(9)}, Gnjilane, Kosovska Kamenica, Vitina, Novo Brdo",
}
